"""
Main composer pipeline using Gemini API.
"""
import os
import json
import traceback
from typing import Optional

import google.generativeai as genai
from app.models import ComposedMessage
from app.suppression import generate_suppression_key

# Ensure API key is configured. The user must provide GEMINI_API_KEY in the environment.
genai.configure(api_key=os.environ.get("GEMINI_API_KEY"))
# Using gemini-3.1-flash-lite which supports response_mime_type and temperature=0 for determinism.
model = genai.GenerativeModel(
    "gemini-3.1-flash-lite",
    generation_config={
        "temperature": 0.0,
        "response_mime_type": "application/json"
    }
)


def compose(
    category: dict,
    merchant: dict,
    trigger: dict,
    customer: Optional[dict] = None
) -> ComposedMessage:
    """
    Main entry point for message composition using Gemini LLM.
    """
    # Deterministic suppression key based on inputs
    supp_key = generate_suppression_key(category, trigger, customer)
    
    prompt = f"""
You are an expert AI merchant assistant named Vera.
You need to write an engagement message based on the following context.
    
Category: {json.dumps(category.get('slug'))}
Voice Tone: {json.dumps(category.get('voice', {}).get('tone'))}
Allowed Vocab: {json.dumps(category.get('voice', {}).get('vocab_allowed', []))}
Taboo Vocab (DO NOT USE): {json.dumps(category.get('voice', {}).get('vocab_taboo', []))}

Merchant Name: {merchant.get('identity', {}).get('name')}
Merchant Offers: {json.dumps(merchant.get('offers', []))}
Merchant Performance: {json.dumps(merchant.get('performance', {}))}

Trigger Kind: {trigger.get('kind')}
Trigger Payload: {json.dumps(trigger.get('payload'))}

Customer Context: {json.dumps(customer) if customer else "None (Message is for the merchant)"}

Task: You must maximize the following 5 dimensions:
1. Specificity (10/10): You MUST include exact numbers, dates, prices, or metric changes from the trigger payload and merchant performance. Do not use vague terms.
2. Category Fit (10/10): The voice register MUST strictly match the specified Voice Tone. Heavily utilize the Allowed Vocab. You are strictly forbidden from using any Taboo Vocab.
3. Merchant Fit (10/10): Reference the Merchant's specific name, their active offers, or their historical performance to prove the message is uniquely for them.
4. Decision Quality (10/10): Make the smartest possible recommendation based on the trigger kind. Don't just state facts—provide a logical business action (e.g., recommend running a specific offer if performance is down, or notify them of a deadline).
5. Engagement Compulsion (10/10): End with a clear, extremely low-friction Call to Action (CTA) that naturally invites a reply (e.g., 'Reply YES to activate', or a simple A/B choice).

Return ONLY a JSON object with the following keys:
- "message": (string) The composed message body.
- "cta": (string) The call to action type (e.g., 'open_ended', 'none', 'link', 'reply_yes').
- "send_as": (string) 'vera' if sending to merchant, 'merchant_on_behalf' if sending to customer.
- "rationale": (string) Detail exactly how you satisfied the 5 dimensions.
"""
    try:
        response = model.generate_content(prompt)
        data = json.loads(response.text)
    except Exception as e:
        print(f"LLM Error in compose: {e}")
        traceback.print_exc()
        data = {
            "message": "Quick update on your listing.",
            "cta": "open_ended",
            "send_as": "vera",
            "rationale": "Fallback composition due to LLM error"
        }
        
    return ComposedMessage(
        message=data.get("message", "Quick update on your listing."),
        cta=data.get("cta", "open_ended"),
        send_as=data.get("send_as", "vera"),
        suppression_key=supp_key,
        rationale=data.get("rationale", "Generated by Gemini")
    )


def handle_reply(
    state: list[dict],
    merchant_message: str,
    merchant: dict,
    customer: Optional[dict] = None
) -> dict:
    """
    Handle multi-turn replies using Gemini LLM.
    """
    prompt = f"""
You are Vera, an AI assistant for {merchant.get('identity', {}).get('name')}.
A user just replied to you. Based on the conversation history, determine the next action.

Conversation History:
{json.dumps(state)}

Latest Reply: "{merchant_message}"

Rules:
1. If the user sends an auto-reply (e.g. "Thank you for contacting us"), or is hostile ("stop", "unsubscribe", "spam"), return action "end".
2. If the user explicitly asks you to wait ("hold on", "give me a minute"), return action "wait" with wait_seconds = 1800.
3. If the user agrees to an action ("ok let's do it", "yes"), return action "send" with a confirmation body and cta "none".
4. Otherwise, return action "send" with an appropriate body continuing the conversation.

Return ONLY a JSON object with:
- "action": (string) "send", "wait", or "end"
- "body": (string) The text message to send (if action is send), otherwise empty string.
- "cta": (string) "open_ended" or "none" (if action is send), otherwise empty string.
- "wait_seconds": (integer) time to wait (if action is wait), otherwise 0.
- "rationale": (string) Explain your decision.
"""
    try:
        response = model.generate_content(prompt)
        data = json.loads(response.text)
        return data
    except Exception as e:
        print(f"LLM Error in handle_reply: {e}")
        traceback.print_exc()
        return {
            "action": "end",
            "rationale": "Fallback to end due to LLM error"
        }
